### ISSUE TITLE
Failing on Chrome Canary builds

### ISSUE THREAD

**Issue by matthewleon** [andrewdavey/immutable-devtools#19] opened 2016-03-24 09:10 UTC
On Chrome build 51.0.2689.0 (actually, for versions stretching back for the preceding week or so), attempts to click on a logged Immutable.js object now result in:

`VM562:9 Custom Formatter Failed: ReferenceError: bindRemoteObject is not defined`

I suspect that there's some kind of permanent change to the Custom Formatter API. A few Google searches have revealed precious little information, sadly.

**Comment by awalkerca** [comment] 2016-03-24 15:31
Version 51.0.2687.0 dev (64-bit)

I'm seeing the same issue on the dev build of stable Chrome.

**Comment by darwin** [comment] 2016-03-24 23:12
Just FYI. We have the same problem here:
https://github.com/binaryage/cljs-devtools/issues/14

**Comment by langpavel** [comment] 2016-03-26 02:50
Hi @darwin. Do you think we should delegate this to Chromium? I'm sure that `bindRemoteObject` is not used in this project.

**Comment by darwin** [comment] 2016-03-26 10:21
The problem seems to be this call:
https://github.com/binaryage/dirac/blob/devtools/front_end/components/CustomPreviewSection.js#L213

It has been there for a long time and that function is not defined anywhere in DevTools code, so I assume it was provided as part of WebKit environment. So I assume someone removed that function or broke it in some way in recent builds. I don't really have time and expertise to go through WebKit/Chromium sources to find what changed at this point.

I believe this will be solved soon when they notice this function is missing. It was probably just renamed or moved elsewhere.

**Comment by mattzeunert** [comment] 2016-03-26 12:00
It's working for me with the current Chrome Canary.

**Comment by darwin** [comment] 2016-03-26 12:13
@mattzeunert Please paste here your Chrome version / OS.

It is still broken in Mac Chrome 51.0.2691.0 canary (64-bit). The bug is reproducible when you try to expand a console log generated via custom formatters (by clicking on it's disclosure triangle).

**Comment by mattzeunert** [comment] 2016-03-26 12:16
@darwin Ah, got it.

**Comment by mattzeunert** [comment] 2016-03-26 16:36
This is the issue in the Chromium bug tracker: https://bugs.chromium.org/p/chromium/issues/detail?id=595206

**Comment by darwin** [comment] 2016-04-01 15:42
I have just raised the issue upstream:
https://bugs.chromium.org/p/chromium/issues/detail?id=599884

**Comment by langpavel** [comment] 2016-04-01 16:45
Thanks @darwin, I starred the issue.

**Comment by darwin** [comment] 2016-04-07 11:28
Fixed in 51.0.2702.0 canary (64-bit)

**Comment by langpavel** [comment] 2016-04-07 22:43
Great! :-)

**Closed by langpavel** 2016-04-07 22:43 UTC
Labels: help wanted, wontfix
